version: '2.1'
services:
  nginx:
    image: nginx:stable-alpine 
    ports:
      #- "8080:80"
      - "443"
      - "80"
    volumes:
      - .:/code
    links:
      - php-fpm
  php-fpm:
    image: ismtlee/php:stable 

